# lustre-zfs-test
#
# playbooks/irods-cluster.yml - Ansible playbook for configuring a test Lustre filesystem with ZFS
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

- hosts: lustre-targets
  become_user: root

  tasks:
    - name: register git repo commit id
      local_action: shell git rev-parse HEAD
      become: no
      register: git_commit_id

    - name: disable selinux
      selinux: state=disabled

    - name: disable firewall
      service: name=firewalld enabled=no state=stopped

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: make sure kernel is up-to-date
      yum: name=kernel state=latest
      register: yum_kernel

    - name: reboot with new kernel
      shell: reboot
      when: yum_kernel['changed'] == true

    - name: wait for rebooted machine to be available
      become: no
      local_action: wait_for host={{ ansible_nodename }} state=started delay=30 timeout=300 connect_timeout=15
      when: yum_kernel['changed'] == true

    - name: necessary package groups
      yum: name={{ item }} state=present
      with_items:
        - "@Development tools"

    - name: necessary package repositories
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - http://download.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm

    - name: necessary packages for maangement
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop

    - name: necessary packages for lustre build
      yum: name={{ item }} state=latest
      with_items:
        - xmlto
        - asciidoc
        - elfutils-libelf-devel
        - zlib-devel
        - binutils-devel
        - newt-devel
        - python-devel
        - hmaccalc
        - perl-ExtUtils-Embed
        - bison
        - elfutils-devel
        - audit-libs-devel
        - python-docutils
        - sg3_utils
        - expect
        - attr
        - lsof
        - quilt
        - libselinux-devel

    - name: apply zfs repo patch
      patch: src=zfs.repo.patch dest=/etc/yum.repos.d/zfs.repo

    - name: zfs packages
      yum: name={{ item }} state=latest
      with_items:
        - zfs
        - libzfs2-devel
        - kmod-spl-devel
        - kmod-zfs-devel

    - name: lustre build script
      template: src=templates/build-lustre-rpms.sh.j2 dest=/tmp/build-lustre-rpms.sh owner=root group=root mode=0755

    - name: run lustre build script if necessary
      shell: /tmp/build-lustre-rpms.sh
      args:
        creates: "{{ lustre_buildroot }}/LUSTRE-VERSION-FILE"

    - name: get lustre version
      shell: "awk '{print $3}' {{ lustre_buildroot }}/LUSTRE-VERSION-FILE"
      register: lustre_version

    - name: lustre packages
      yum: name={{ item }} state=present
      with_items:
        - /tmp/lustre-release/kmod-lustre-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/kmod-lustre-osd-zfs-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/kmod-lustre-tests-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-debuginfo-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-iokit-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-osd-zfs-mount-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-tests-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm

    - name: lustre lnet configuration
      template: src=templates/lustre-lnet.conf.j2 dest=/etc/modprobe.d/lnet.conf owner=root group=root mode=0644

    - name: lustre ldev configuration
      template: src=templates/lustre-ldev.conf.j2 dest=/etc/ldev.conf owner=root group=root mode=0644

    - name: create test lustre filesystem mds target
      command: mkfs.lustre --mgs --backfstype=zfs --fsname=lustre --device-size=1048576 lustre-mgs/mgs /tmp/lustre-mgs
      args:
        creates: /tmp/lustre-mgs

    - name: create test lustre filesystem mdt0 target
      command: mkfs.lustre --mdt --backfstype=zfs --fsname=lustre --index=0 --mgsnode={{ lustre_target_mgs }}@tcp --device-size=1048576 lustre-mdt0/mdt0 /tmp/lustre-mdt0
      args:
        creates: /tmp/lustre-mdt0

    - name: create test lustre filesystem ost0 target
      command: mkfs.lustre --ost --backfstype=zfs --fsname=lustre --index=0 --mgsnode={{ lustre_target_mgs }}@tcp --device-size=1048576 lustre-ost0/ost0 /tmp/lustre-ost0
      args:
        creates: /tmp/lustre-ost0

    - name: lustre filesystem started and enabled (dirty workaround for ansible bug with sysv services and systemd)
      shell: service lustre start && chkconfig lustre on

  handlers:
    - include: handlers/main.yml
