# lustre-zfs-test
#
# playbooks/irods-cluster.yml - Ansible playbook for configuring a test Lustre filesystem with ZFS
# Author: Ilari Korhonen, KTH Royal Institute of Technology

---

- hosts: lustre-targets
  become_user: root

  tasks:
    - name: register git repo commit id
      local_action: shell git rev-parse HEAD
      become: no
      register: git_commit_id

    - name: disable selinux
      selinux: state=disabled

    - name: disable firewall
      service: name=firewalld enabled=no state=stopped

    - name: "Build hosts file"
      lineinfile: dest=/etc/hosts regexp='.*{{ item }}$' line="{{ hostvars[item].ansible_eth1.ipv4.address }} {{item}}" state=present
      when: hostvars[item].ansible_eth1.ipv4.address is defined
      with_items: "{{ groups['all'] }}"

    - name: make sure kernel is up-to-date
      yum: name=kernel state=latest
      register: yum_kernel

    - name: reboot machine in case of kernel upgrade
      shell: reboot
      async: 0
      poll: 0
      when: yum_kernel['changed'] == true

    - name: wait for rebooted machine to be available
      local_action: wait_for_host={{ ansible_ssh_host }} state=started
      when: yum_kernel['changed'] == true

    - name: necessary package groups
      yum: name={{ item }} state=present
      with_items:
        - "@Development tools"

    - name: necessary package repositories
      yum: name={{ item }} state=present
      with_items:
        - epel-release
        - http://download.zfsonlinux.org/epel/zfs-release.el7.noarch.rpm

    - name: necessary packages for maangement
      yum: name={{ item }} state=latest
      with_items:
        - psmisc
        - net-tools
        - htop
        - iotop
        - iftop

    - name: necessary packages for lustre build
      yum: name={{ item }} state=latest
      with_items:
        - xmlto
        - asciidoc
        - elfutils-libelf-devel
        - zlib-devel
        - binutils-devel
        - newt-devel
        - python-devel
        - hmaccalc
        - perl-ExtUtils-Embed
        - bison
        - elfutils-devel
        - audit-libs-devel
        - python-docutils
        - sg3_utils
        - expect
        - attr
        - lsof
        - quilt
        - libselinux-devel

    - name: apply zfs repo patch
      patch: src=zfs.repo.patch dest=/etc/yum.repos.d/zfs.repo

    - name: zfs packages
      yum: name={{ item }} state=latest
      with_items:
        - zfs
        - libzfs2-devel
        - kmod-spl-devel
        - kmod-zfs-devel

    - name: get lustre version
      shell: awk '{print $3}' /tmp/lustre-release/LUSTRE-VERSION-FILE
      register: lustre_version

    - name: lustre packages
      yum: name={{ item }} state=present
      with_items:
        - /tmp/lustre-release/kmod-lustre-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/kmod-lustre-osd-zfs-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/kmod-lustre-tests-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-debuginfo-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-iokit-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-osd-zfs-mount-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
        - /tmp/lustre-release/lustre-tests-{{ lustre_version['stdout'] }}-1.el7.centos.x86_64.rpm
